version: '3.7'
services:
  rs:
    image: it21/rs:latest
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # 监听宿主机的80端口
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      rs:
        condition: service_healthy

volumes:
  nginx_config: